stages:
  - setup
  - deploy  

install-tools:
  stage: setup

  before_script:
      - echo installing aws cli 
      - apt-get update
      - apt-get install zip
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - aws --version
      - wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt update && apt install terraform
      - terraform --version
      - apt-get install git
  script: 
      - echo "tools installed"

# deploy-dev:
#   stage: deploy

#   script: 

#       -  





