name: dev terraform reusable workflow

on:
    workflow_dispatch:
        inputs:
            environment:
                required: true
                default: dev
                type: choice
                options: 
                    - dev
                    - prod


jobs: 
  deploy-dev-prod-reusable:
 
     uses: ./.github/workflows/terraform_deployment.yaml
     with:
          environment: ${{ inputs.environment }}

     secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


    
